### ISSUE TITLE
登录后无法下载视频，所有视频都无法正常解析

### ISSUE THREAD

**Issue by GaoHaHa-IronMan** [iuroc/bilidown#2]
> 请输入 Bilibili 视频链接: https://www.bilibili.com/video/BV14GpHe9ESf/?spm_id_from=333.1007.tianma.8-3-29.click
❗️ 视频解析失败, 请重试

**Comment by iuroc** [comment]
尽快修复

**Comment by iuroc** [comment]
已修复因为缺少 `User-Agent` 请求头导致 Bilibili 响应中出现验证码检查进而导致无法解析视频的问题。

同时升级到 v1.0.3，支持终端扫码登录，无需依赖浏览器，支持 Windows、Mac、Linux。 https://github.com/iuroc/bilidown/commit/6dc1dc9418c1aef64ddb435bb1efd80b1095b72d
