### ISSUE TITLE
客户端无法扫码识别

### ISSUE THREAD

**Issue by jmui114** [iuroc/bilidown#3]
v1.0.3 版本，选项1登录账号的二维码，无论是手机客户端还是平板客户端，均无法识别二维码内容
手机：IQOO 10
平板：vivoPad 3Pro
客户端：国内版B站客户端 + Google版B站客户端

**Comment by iuroc** [comment]
请问下您的操作系统和终端是什么，例如 Windows 11 CMD

我在我的 Windows 11 CMD 上面测试是没问题的，我将二维码原样截图如下，你可以扫描看下有没有效果：

![image](https://github.com/user-attachments/assets/6c9c029d-2e76-4f65-bc90-7fbbb5ce195c)

**Comment by jmui114** [comment]
> 请问下您的操作系统和终端是什么，例如 Windows 11 CMD
> 
> 我在我的 Windows 11 CMD 上面测试是没问题的，我将二维码原样截图如下，你可以扫描看下有没有效果：
> 
> 或者您提供一下具体的错误截图，方便我分析。
> 
> <img alt="" width="200" src="https://private-user-images.githubusercontent.com/61752998/366328569-6c9c029d-2e76-4f65-bc90-7fbbb5ce195c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzgwNzcsIm5iZiI6MTcyNjAzNzc3NywicGF0aCI6Ii82MTc1Mjk5OC8zNjYzMjg1NjktNmM5YzAyOWQtMmU3Ni00ZjY1LWJjOTAtN2ZiYmI1Y2UxOTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA2NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNzI4MTk0MTZjMzU1NWI3M2IyNWZjNzdlNjllNWUwZGFiZjMwZWE1MDhjODdkNDU0NWNhZjcyM2QxY2FmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dWtObOB5Ve2QNf7L8xmn1UeBtJN4jiWQGB3XsXPJo0">

版本	Windows 11 IoT 企业版 LTSC
版本号	24H2
安装日期	‎2024/‎9/‎5
操作系统版本	26100.1457
体验	Windows Feature Experience Pack 1000.26100.11.0
---
终端：CMD
版本：Microsoft Windows [版本 10.0.26100.1457]
---
大佬你上面的二维码我是可以正常扫码识别的，但我自己操作得到的二维码显示效果不一样，换过3台电脑（win10+win11），都是二维码显示效果异常如下。
---
![image](https://github.com/user-attachments/assets/dc00a8f9-d566-4419-817a-1bba52b85e01)
![image](https://github.com/user-attachments/assets/62617c28-5a29-4d29-88d0-e533afc6d634)

**Comment by iuroc** [comment]
尝试不使用管理员身份运行，本项目二维码输入基于 github.com/skip2/go-qrcode 项目实现，在管理员的模式下，CMD 输出二维码会出问题。

**Comment by lmb1113** [comment]
> 尝试不使用管理员身份运行，本项目二维码输入基于 [go-qrcode](https://github.com/skip2/go-qrcode) 项目实现，在管理员的模式下，CMD 输出二维码会出问题。
> 
> 或者通过 `Win + R` 输入 `cmd`，然后通过 bilidown.exe 的路径启动。
> 
> 本质原因是，管理员模式下的 Windows CMD 无法显示 `\u2580`。

控制台输出二维码文本方式对于一些特殊的字体不太兼容，我更换了新的登录二维码打开方式#4

**Comment by iamlinkent** [comment]
> 尝试不使用管理员身份运行，本项目二维码输入基于 [go-qrcode](https://github.com/skip2/go-qrcode) 项目实现，在管理员的模式下，CMD 输出二维码会出问题。
> 
> 或者通过 `Win + R` 输入 `cmd`，然后通过 bilidown.exe 的路径启动。
> 
> 本质原因是，管理员模式下的 Windows CMD 无法显示 `\u2580`。

按你的方法也不行！

**Comment by iuroc** [comment]
> > 尝试不使用管理员身份运行，本项目二维码输入基于 [go-qrcode](https://github.com/skip2/go-qrcode) 项目实现，在管理员的模式下，CMD 输出二维码会出问题。
> > 或者通过 `Win + R` 输入 `cmd`，然后通过 bilidown.exe 的路径启动。
> > 本质原因是，管理员模式下的 Windows CMD 无法显示 `\u2580`。
> 
> 按你的方法也不行！

下一个版本修复，最近忙着找工作，没时间修改，抱歉。
